### ISSUE TITLE
Option in settings causes a crash (Android) 

### ISSUE THREAD

**Issue by Wojtaz0w** [uazo/bromite-buildtools#215]
1.Click on "security check" (or something like that) 
2.Chromite (my favourite name for this fork) crashes
Log: https://paste.crdroid.net/arto1r
```
msg: java.lang.ClassNotFoundException: org.chromium.chrome.browser.safety_check.SafetyCheckSettingsFragment
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bromite.bromite.dev/org.chromium.chrome.browser.settings.SettingsActivity}: x00: Unable to instantiate fragment org.chromium.chrome.browser.safety_check.SafetyCheckSettingsFragment: make sure class name exists
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
Caused by: x00: Unable to instantiate fragment org.chromium.chrome.browser.safety_check.SafetyCheckSettingsFragment: make sure class name exists
	at T00.c(chromium-ChromePublic.apk-stable-567212715:30)
	at androidx.fragment.app.c.X(chromium-ChromePublic.apk-stable-567212715:9)
	at org.chromium.chrome.browser.settings.SettingsActivity.onCreate(chromium-ChromePublic.apk-stable-567212715:112)
	at android.app.Activity.performCreate(Activity.java:8311)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.chromium.chrome.browser.safety_check.SafetyCheckSettingsFragment
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at T00.b(chromium-ChromePublic.apk-stable-567212715:28)
	at T00.c(chromium-ChromePublic.apk-stable-567212715:3)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.chromium.chrome.browser.safety_check.SafetyCheckSettingsFragment
	at mn.findClass(chromium-ChromePublic.apk-stable-567212715:79)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 22 more
```
This is the problematic setting:
![Screenshot_20230521-224313_Chromium.png](https://github.com/uazo/bromite-buildtools/assets/104674625/27136d2b-cc95-4b97-96dd-3168f593221a)

**Comment by eskimododo** [comment]
Can confirm.. clicking "safety check" in settings causes chromite to crash on Android..

**Comment by uazo** [comment]
thank you, I already knew it https://github.com/uazo/bromite-buildtools/issues/175#issuecomment-1537486851
