### ISSUE TITLE
building cromite with docker

### ISSUE THREAD

**Issue by LeOS-GSI** [uazo/bromite-buildtools#337]
Where can I find a howto building cromite with docker ? As far as I know, you are suing docker

**Comment by LeOS-GSI** [comment]
I have followed you complete script. But still getting this error when running
`~/gh-runner/bromite-buildtools/images/github-runner$ sudo ./start-runner.sh` or without sudo
`~/gh-runner/bromite-buildtools/images/github-runner$ ./start-runner.sh`

`--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

New-line characters are not allowed in header values.
.path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Starting Runner listener with startup type: service
Started listener process
Started running service
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.    at GitHub.Runner.Listener.Configuration.ConfigurationManager.LoadSettings()
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
   at GitHub.Runner.Listener.Program.MainAsync(IHostContext context, String[] args)
Runner listener exited with error code 1
Runner listener exit with terminated error, stop the service, no retry needed.
sudo: unable to resolve host 2c087aad536d: Temporary failure in name resolution
 * Stopping Docker: docker                                                                                                                    [ OK ] 
Unrecognized command-line input arguments for command remove: 'unattended'. For usage refer to: .\config.cmd --help or ./config.sh --help

# Runner removal

Cannot connect to server, because config files are missing. Skipping removing runner from the server.
Does not exist. Skipping Removing .credentials
Does not exist. Skipping Removing .runner

You can stop now
Starting Proxy Support
sudo: unable to resolve host 1f230ae55c46: Temporary failure in name resolution
sudo: unable to resolve host 1f230ae55c46: Temporary failure in name resolution
Starting supervisor (Docker)
sudo: unable to resolve host 1f230ae55c46: Temporary failure in name resolution
mount: /sys/fs/cgroup/cpuset: permission denied.
mount: /sys/fs/cgroup/cpu: permission denied.
mount: /sys/fs/cgroup/cpuacct: permission denied.
mount: /sys/fs/cgroup/blkio: permission denied.
mount: /sys/fs/cgroup/memory: permission denied.
mount: /sys/fs/cgroup/devices: permission denied.
mount: /sys/fs/cgroup/freezer: permission denied.
mount: /sys/fs/cgroup/net_cls: permission denied.
mount: /sys/fs/cgroup/perf_event: permission denied.
mount: /sys/fs/cgroup/net_prio: permission denied.
mount: /sys/fs/cgroup/hugetlb: permission denied.
mount: /sys/fs/cgroup/pids: permission denied.
^CYou can stop now
^C
ich@mint21:~/gh-runner/bromite-buildtools/images/github-runner$ ^C
`
